// <auto-generated />
using System;
using GlonassSoftTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GlonassSoftTest.Migrations
{
    [DbContext(typeof(DbInteractor))]
    partial class DbInteractorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("GlonassSoftTest.UserStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserStats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("539d5c23-aec2-4a22-a251-8af5a64cd69c"),
                            EmploymentDate = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xарламов Д.Д."
                        },
                        new
                        {
                            Id = new Guid("0986a4c1-48f3-4093-be14-72636de5036a"),
                            EmploymentDate = new DateTime(2022, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Сергеев С.Т."
                        },
                        new
                        {
                            Id = new Guid("8a43109b-ee6d-4914-b773-c6b5f910734c"),
                            EmploymentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Смирнов А.В."
                        },
                        new
                        {
                            Id = new Guid("e4ae22fe-6791-4c3d-9378-d0c4d38b4062"),
                            EmploymentDate = new DateTime(2021, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Куприенко Л.В."
                        },
                        new
                        {
                            Id = new Guid("7446b452-e059-4a09-a25e-dc9fa21a70b2"),
                            EmploymentDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Волкова А.В."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
